# -*- coding: utf-8 -*-
"""Breast Cancer ML Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WH-jBfme3jG5UdsFKzYHJX_pt4A5Zn6T

# Import the Data via Kaggle
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("uciml/breast-cancer-wisconsin-data")

print("Path to dataset files:", path)

import pandas as pd
import seaborn as sns

data = pd.read_csv("/kaggle/input/breast-cancer-wisconsin-data/data.csv")

"""# EDA"""

data.head(5)

data.info()

"""# Data Cleaning"""

sns.heatmap(data.isnull()) # Note unnamed column is full of NaN

data.drop(["Unnamed: 32", "id"], axis=1, inplace=True) # Drop empty column and irrelevant "id" column.

data.diagnosis = [1 if value == "M" else 0 for value in data.diagnosis] # Convert M (malignant) and B(benign) into 1 and 0 integers.

data['diagnosis'].value_counts().plot(kind='bar') # Plot to see distribution of diagnosis in dataset

# Divide into target variable and predictors
y = data['diagnosis']
X = data.drop(['diagnosis'], axis=1)

"""# Data Normalisation"""

from sklearn.preprocessing import StandardScaler

# Create a scaler object
scaler = StandardScaler() #Sklearn tool

# Fit scaler to data and transform the data
X_scaled = scaler.fit_transform(X)

"""# Split the Data"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.3, random_state = 42)

"""# Train the model"""

from sklearn.linear_model import LogisticRegression

# Create the lr model
lr = LogisticRegression()

# Train the model on the training data
lr.fit(X_train, y_train)

# Predict the target variable on the test data
y_pred = lr.predict(X_test)

y_pred # This is the prediction made by "lr" model

"""# Evalation of the Model"""

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy: .2f}")

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

"""Note: There are more evaluation steps which could possibly be performed.

Now an application can be built around the model "lr"!
"""